### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by HomCatch** [lgy1027/fabric-network#1]
k8s的具体操作流程能不能详细介绍一下？

**Comment by lgy1027** [comment]
部署命名空间，起order.yaml,再peer.yaml，如果部署web项目改dockerfile,在修改server.yaml的镜像源和启动参数

**Comment by lgy1027** [comment]
> k8s的具体操作流程能不能详细介绍一下？

部署命名空间，起order.yaml,再peer.yaml，如果部署web项目改dockerfile,在修改server.yaml的镜像源和启动参数
